version: '3.7'
services:
  db:
    container_name: geoserver-db
    image: mdillon/postgis:11
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
      #POSTGRES_USER:
      #POSTGRES_DB:
      #POSTGRES_INITDB_ARGS:
      #POSTGRES_INITDB_XLOGDIR:
    # I don't really need to put the PostGIS data in a separate volume.
    # Can having it in a volume make it easier to back up?
    # I think it's on SSD where it is, so fast but not a lot of space.
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
    restart: unless-stopped

  geoserver:
    container_name: geoserver
    build:
        context: geoserver
    environment:
      GEOSERVER_DATA_DIR: /geoserver
    # Have to use a volume for this, since it's shared with geowebcache
    volumes:
      - type: volume
        source: geoserver_data
        target: /geoserver
    restart: unless-stopped

  geowebcache:
    container_name: geoserver-geowebcache
    image: geoceg/geowebcache:latest
    environment:
      GEOWEBCACHE_DATA_DIR: /geowebserver/gwc
    volumes:
      - type: volume
        source: geoserver_data
        target: /geoserver
    depends_on:
      - geoserver
    restart: unless-stopped
    
  pgadmin:
    container_name: geoserver-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      # Added SCRIPT_NAME to solve this problem: https://stackoverflow.com/questions/46381668/pgadmin4-wont-work-in-specific-location-behind-nginx
      SCRIPT_NAME: /pgadmin4

  # Support full HTTP and HTTPS
  # Provides proxies for GeoServer, GeoWebCache, and PGadmin
  nginx:
    build:
        context: nginx
    command: /bin/bash -c "sed 's/%VIRTUALHOST%/${VIRTUALHOST}/' < /etc/nginx/conf.d/virtualhost.conf.template > /etc/nginx/conf.d/virtualhost.conf && nginx -g 'daemon off;'"
    container_name: geoserver-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: volume
        source: static_content
        target: /var/www/html/
      - type: bind
        source: ./nginx/virtualhost.conf.template
        target: /etc/nginx/conf.d/virtualhost.conf.template
      - type: bind
        source: ./nginx/proxy.d
        target: /etc/nginx/proxy.d
      - type: bind
        source: ${SSL_CERT}
        target: /tmp/ssl_cert.pem
      - type: bind
        source: ${SSL_KEY}
        target: /tmp/ssl_key.pem
      - type: bind
        source: ${SSL_DHPARAMS}
        target: /tmp/dhparams.pem
    depends_on:
      - geoserver
      - pgadmin
    restart: unless-stopped

volumes:
  db_data:
    name: geoserver_postgis_data

  static_content:
    name: geoserver_static_content

  geoserver_data:
    name: geoserver_data
